import frappe
from erpnext.stock.doctype.purchase_receipt.purchase_receipt import PurchaseReceipt
from frappe.utils import flt, cstr, now, get_datetime_str, file_lock, date_diff, now_datetime, cint
from frappe import _, msgprint, is_whitelisted
from metactical.custom_scripts.utils.metactical_utils import queue_action, post_to_rocket_chat
from metactical.procurement_v3.utils import F, mirror_po3_status, v3_reconcile
from frappe.model.docstatus import DocStatus

class CustomPurchaseReceipt(PurchaseReceipt):
	def validate(self):
		super(CustomPurchaseReceipt, self).validate()
		if self.purchase_order:
			for d in self.items:
				d.purchase_order = self.purchase_order

		self.validate_barcodes()
		self.validate_accepted_warehouse_permission()

	def validate_accepted_warehouse_permission(self):
		# Metactical Customization: Validate that user has permission to use the accepted warehouse
		user = frappe.session.user
		setting_exists = frappe.db.get_value("Warehouse User Permissions", filters={"user": user})
		if setting_exists:
			settings = frappe.get_doc("Warehouse User Permissions", setting_exists)
			permitted_warehouses = [row.warehouse for row in settings.purchase_receipt_accepted_warehouse]

			if permitted_warehouses:
				if self.set_warehouse and self.set_warehouse not in permitted_warehouses:
					frappe.throw("Warehouse {} not in list of warehouse allowed for user {}".format(self.set_warehouse, user))

				for row in self.items:
					# Metactical Customization: Purchase Receipt Item's "Accepted Warehouse"
					# field's actual fieldname is "warehouse" (label is "Accepted Warehouse")
					if row.warehouse and row.warehouse not in permitted_warehouses:
						frappe.throw("Warehouse {} not in list of warehouse allowed for user {}".format(row.warehouse, user))

	def validate_barcodes(self):
		for item in self.items:
			if not item.barcode:
				barcode = frappe.db.get_value("Item Barcode", {"parent": item.item_code}, "barcode")
				if barcode:	
					item.barcode = barcode
     
	def save(self):
		if self.docstatus == DocStatus.submitted() and len(self.items) > 100 and \
			self.ais_queue_status and self.ais_queue_status != "Queued":
			msgprint(
				_(
					"The task has been enqueued as a background job. In case there is \
					any issue on processing in background, the system will add a comment \
					about the error on this document and revert to the Draft stage"
				)
			)
			queue_action(self, "submit", timeout=2000)
		else:
			super().save()

	def before_submit(self):
		self.barcode_check()

	def barcode_check(self):
		for item in self.items:
			barcode_exists = frappe.db.exists("Item Barcode", {"parent": item.item_code})
			if not barcode_exists:
				frappe.throw(f"Error: Please add a barcode for item {item.item_code}")

	def on_submit(self):
		super(CustomPurchaseReceipt, self).on_submit()
		post_rc_message(self)
		v3_sync_to_po3(self)

	def on_cancel(self):
		super(CustomPurchaseReceipt, self).on_cancel()
		v3_cancel_sync_to_po3(self)
		
def post_rc_message(doc):
	if not doc.is_return and doc.company == "International Camouflage Ltd":
		active_warehouse = "W01-WHS-Active Stock - ICL"
		po = frappe.get_doc("Purchase Order", doc.purchase_order)

		# Some POs don't have set_warehouse set on the header, so fall back to
		# checking each item's Target Warehouse.
		is_active = po.set_warehouse == active_warehouse
		if not po.set_warehouse:
			is_active = any(item.warehouse == active_warehouse for item in po.items)

		if is_active:
			frappe.enqueue(
				send_pdf_to_rocket_chat,
				name=doc.name
			)


# ---------------------------------------------------------------------------
# Migrated from Server Script "Native PR Sync To PO3"
# (DocType Event / After Submit on Purchase Receipt).
#
# A native receipt raised outside the V3 flow (PPS, Desk, anything) still has
# to land on the PO3 twin. Receipts that a Goods Receipt V3 created are skipped
# here, because GR3 already rolled itself up at Post time.
# ---------------------------------------------------------------------------
def v3_sync_to_po3(doc):
	# Native PR submitted (by PPS, Desk, or anything else). If its PO has a V3
	# twin, roll the receipt into the PO3 lines - unless this PR was generated by
	# a Goods Receipt V3, which already rolled itself up at Post time.
	po_names = set()
	for d in doc.items:
		if d.purchase_order:
			po_names.add(d.purchase_order)

	for po_name in po_names:
		po3_name = frappe.db.get_value("Purchase Order V3", {"erp_purchase_order": po_name}, "name")
		if not po3_name:
			continue
		po3 = frappe.get_doc("Purchase Order V3", po3_name)
		by_erp = {}
		for r in po3.items:
			if r.erp_po_item:
				by_erp[r.erp_po_item] = r
		touched = False
		for d in doc.items:
			if d.purchase_order != po_name:
				continue
			if d.get("neb_source_doctype") == "Goods Receipt V3":
				continue
			r = by_erp.get(d.purchase_order_item)
			if not r:
				continue
			acc = F(r.accepted_qty) + F(d.qty)
			rej = F(r.rejected_qty) + F(d.rejected_qty)
			rec = F(r.received_qty) + F(d.qty) + F(d.rejected_qty)
			upd = {"received_qty": rec, "accepted_qty": acc, "rejected_qty": rej}
			if rec >= F(r.qty):
				upd["line_status"] = "Received"
				upd["over_qty"] = rec - F(r.qty)
				upd["short_qty"] = 0
				if r.backorder_status == "Open":
					upd["backorder_status"] = "Fulfilled"
			elif r.backorder_status == "Open":
				upd["line_status"] = "Back-ordered"
			else:
				upd["line_status"] = "Partial" if F(r.confirmed_qty) else "Open"
			frappe.db.set_value("Purchase Order V3 Item", r.name, upd)
			touched = True
		if not touched:
			continue
		fresh = frappe.get_all("Purchase Order V3 Item", filters={"parent": po3_name},
			fields=["line_status", "received_qty"])
		all_terminal = bool(fresh)
		any_short = False
		any_received = False
		for r in fresh:
			if r.line_status not in ("Received", "Closed Short", "Cancelled", "Supplier Stock Out", "Discontinued"):
				all_terminal = False
			if r.line_status in ("Closed Short", "Cancelled", "Supplier Stock Out", "Discontinued"):
				any_short = True
			if F(r.received_qty) > 0:
				any_received = True
		hdr = {}
		if all_terminal:
			hdr["receipt_status"] = "Closed Short" if any_short else "Received"
			hdr["workflow_state"] = "Closed Short" if any_short else "Closed"
		elif any_received:
			hdr["receipt_status"] = "Partially Received"
			if po3.workflow_state in ("Sent to Supplier", "Acknowledged"):
				hdr["workflow_state"] = "Partially Received"
		if hdr:
			frappe.db.set_value("Purchase Order V3", po3_name, hdr)

	mirror_po3_status(po3_name)

	for po_name in po_names:
		p3 = frappe.db.get_value("Purchase Order V3", {"erp_purchase_order": po_name}, "name")
		if p3:
			v3_reconcile(p3)




# ---------------------------------------------------------------------------
# Migrated from Server Script "Native PR Cancel Sync To PO3"
# (DocType Event / After Cancel on Purchase Receipt).
#
# Rolls the cancelled receipt's quantities back off the PO3 lines, re-derives
# each line status from what is left, and steps the order back from
# Received / Closed to Partially Received or Acknowledged as appropriate.
# ---------------------------------------------------------------------------
def v3_cancel_sync_to_po3(doc):
	po_names = set()
	for d in doc.items:
		if d.purchase_order:
			po_names.add(d.purchase_order)

	for po_name in po_names:
		po3_name = frappe.db.get_value("Purchase Order V3", {"erp_purchase_order": po_name}, "name")
		if not po3_name:
			continue
		po3 = frappe.get_doc("Purchase Order V3", po3_name)
		by_erp = {}
		for r in po3.items:
			if r.erp_po_item:
				by_erp[r.erp_po_item] = r
		touched = False
		for d in doc.items:
			if d.purchase_order != po_name:
				continue
			if d.get("neb_source_doctype") == "Goods Receipt V3":
				continue
			r = by_erp.get(d.purchase_order_item)
			if not r:
				continue
			acc = F(r.accepted_qty) - F(d.qty)
			rej = F(r.rejected_qty) - F(d.rejected_qty)
			rec = F(r.received_qty) - F(d.qty) - F(d.rejected_qty)
			if acc < 0:
				acc = 0
			if rej < 0:
				rej = 0
			if rec < 0:
				rec = 0
			upd = {"received_qty": rec, "accepted_qty": acc, "rejected_qty": rej}
			if rec >= F(r.qty):
				upd["line_status"] = "Received"
			elif r.backorder_status == "Open":
				upd["line_status"] = "Back-ordered"
			elif rec > 0 or F(r.confirmed_qty):
				upd["line_status"] = "Partial"
				upd["short_qty"] = 0
			else:
				upd["line_status"] = "Open"
				upd["short_qty"] = 0
			frappe.db.set_value("Purchase Order V3 Item", r.name, upd)
			touched = True
		if touched and po3.workflow_state in ("Closed", "Closed Short", "Received"):
			frappe.db.set_value("Purchase Order V3", po3_name,
				{"workflow_state": "Partially Received", "receipt_status": "Partially Received"})

	mirror_po3_status(po3_name)


def validate(self, method):
	if self.set_warehouse:
		for item in self.items:
			if item.warehouse != self.set_warehouse:
				item.warehouse = self.set_warehouse
			
@frappe.whitelist()
def get_accepted_warehouse(doctype, txt, searchfield, start, page_len, filters):
	user = filters.get("user")
	warehouses = []
	if user:
		setting_exists = frappe.db.get_value("Warehouse User Permissions", filters={"user": user})
		if setting_exists:
			warehouses = frappe.db.sql("""SELECT warehouse FROM `tabUser Permitted Warehouse`
							WHERE warehouse LIKE %(txt)s AND parent= %(parent)s
							AND parentfield='purchase_receipt_accepted_warehouse'""",
							{
								'txt': "%%%s%%" % txt,
								'parent': setting_exists
							})

		if not setting_exists or not warehouses:
			#Retrun all warehouses
			warehouses = frappe.db.sql("""SELECT name FROM `tabWarehouse` WHERE is_group=0 AND disabled=0 AND name LIKE %(txt)s""", {'txt': "%%%s%%" % txt})
	return warehouses

@frappe.whitelist()
def get_pr_items(docname):
	items = []
	added_items = []
	doc = frappe.get_doc('Purchase Receipt', docname)
	for item in doc.items:
		if item.item_code not in added_items:
			items.append(item)
			added_items.append(item.item_code)
		else:
			for i in items:
				if i.item_code == item.item_code:
					i.update({
						'qty': i.qty + item.qty
					})
	return items


@frappe.whitelist()
def get_print_format(docname):
	doc = frappe.get_doc('Purchase Receipt', docname)
	return frappe.get_print(doctype=doc.doctype, name=doc.name, print_format="Purchase Receipt Barcode - V2", no_letterhead=0)


@frappe.whitelist()
def send_pdf_to_rocket_chat(name):
    try:
        doc = frappe.get_doc("Purchase Receipt", name)

        html = frappe.get_print(
            "Purchase Receipt",
            name,
            print_format="PR Report V5",
            no_letterhead=0,
        )
        pdf_content = frappe.utils.pdf.get_pdf(html)

        supplier = frappe.get_doc("Supplier", doc.supplier)
        po = doc.purchase_order
        if supplier.country == "China":
            filename = f"China PO-{po}.pdf"
        else:
            filename = f"{supplier.name} PO-{po}.pdf"

        post_to_rocket_chat(
            doc=doc,
            msg=None,
            attachment=pdf_content,
            filename=filename,
        )
    except Exception:
        frappe.log_error(
            title="Rocket Chat PDF Upload Failed",
            message=frappe.get_traceback(),
        )