# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from . import __version__ as _app_version

app_name = "metactical"
app_title = "Storebuilder Commerce"
app_publisher = "Storebuilder Commerce Inc"
app_description = "Storebuilder Commerce Inc ERPNext App"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = ""
app_license = "MIT"
app_logo_url =  "/assets/metactical/images/storebuilder-logo.png"

add_to_apps_screen = [
	{
		"name": "storebuilder-commerce",
		"logo": "/assets/metactical/images/storebuilder-logo.png",
		"title": "Storebuilder Commerce Inc",
		"route": "/app/home",
		"has_permission": "metactical.check_app_permission",
	}
]

# Includes in <head>
# ------------------

# include js, css files in header of desk.html
app_include_css = ["metactical.bundle.scss", "/assets/metactical/css/metactical_task.css"]
app_include_js = ["metactical.bundle.js"]

# include js, css files in header of web template
# web_include_css = "/assets/metactical/css/metactical.css"
web_include_css = [
	"/assets/metactical/node_modules/intl-tel-input/build/css/intlTelInput.css", 
	"/assets/metactical/css/metactical_time_tracker.css"
]
# web_include_js = "/assets/metactical/js/metactical.js"
web_include_js = "/assets/metactical/node_modules/intl-tel-input/build/js/intlTelInput.js"

# include js in page
# page_js = {"page" : "public/js/file.js"}

# include js in doctype views
doctype_js = {
	"Sales Order" : "custom_scripts/sales_order/sales_order.js",
	"Pick List": "custom_scripts/pick_list/pick_list.js",
	"Stock Entry": "custom_scripts/stock_entry/stock_entry.js",
	"Sales Invoice": "custom_scripts/sales_invoice/sales_invoice.js",
	"Purchase Order": "custom_scripts/purchase_order/purchase_order.js",
	"Material Request": "custom_scripts/material_request/material_request.js",
	"Payment Entry": "custom_scripts/payment_entry/payment_entry.js",
	"Employee": "custom_scripts/employee/employee.js",
	"Stock Reconciliation": "custom_scripts/stock_reconciliation/stock_reconciliation.js",
	"Purchase Receipt": "custom_scripts/purchase_receipt/purchase_receipt.js",
	"Customer": "custom_scripts/customer/customer.js",
	"Shipment": "custom_scripts/shipment/shipment.js",
	"Delivery Note": "custom_scripts/delivery_note/delivery_note.js",
	"Project": "custom_scripts/project/project.js",
	"Task": "custom_scripts/task/task.js",
	"Warehouse": "custom_scripts/warehouse/warehouse.js",
	"Contact": "custom_scripts/contact/contact.js",
	"Item": "custom_scripts/item/item.js",
	"POS Profile": "custom_scripts/pos_profile/pos_profile.js",
 	"Item Group": "custom_scripts/item_group/item_group.js",
	"Packing Slip": "custom_scripts/packing_slip/packing_slip.js",
	"Email Campaign": "custom_scripts/email_campaign/email_campaign.js",
	"BOM" : "custom_scripts/bom/bom.js",
	"Operation": "custom_scripts/bom_operation/bom_operation.js"
}
# doctype_js = {"doctype" : "public/js/doctype.js"}
#doctype_list_js = {"doctype" : "public/js/doctype_list.js"}
doctype_list_js = {
	"Stock Reconciliation": "custom_scripts/stock_reconciliation/stock_reconciliation_list.js",
	"Task": "custom_scripts/task/task_list.js",
	"Project": "custom_scripts/project/project_list.js",
	"Pick List": "custom_scripts/pick_list/pick_list_list.js",
	"Item": "custom_scripts/item/item_list.js",
}
# doctype_tree_js = {"doctype" : "public/js/doctype_tree.js"}
# doctype_calendar_js = {"doctype" : "public/js/doctype_calendar.js"}

# Home Pages
# ----------

# application home page (will override Website Settings)
home_page = "login"

# website user home page (by Role)
# role_home_page = {
#	"Role": "home_page"
# }

# Website user home page (by function)
# get_website_user_home_page = "metactical.utils.get_home_page"

# Generators
# ----------

# automatically create page for each record of this doctype
# website_generators = ["Web Page"]

# Installation
# ------------

# before_install = "metactical.install.before_install"
# after_install = "metactical.install.after_install"

# Desk Notifications
# ------------------
# See frappe.core.notifications.get_notification_config

# notification_config = "metactical.notifications.get_notification_config"

website_context = {
	"favicon": "/assets/metactical/images/favicon.ico",
	"splash_image": "/assets/metactical/images/storebuilder.svg",
}

# Permissions
# -----------
# Permissions evaluated in scripted ways

permission_query_conditions = {
	"End of Day Closing": "metactical.metactical.doctype.end_of_day_closing.end_of_day_closing.get_permission_query_conditions"
}

#
has_permission = {
	"End of Day Closing": "metactical.metactical.doctype.end_of_day_closing.end_of_day_closing.has_permission"
}


# Document Events
# ---------------
# Hook on document methods and events

doc_events = {
	"Purchase Order": {
		"after_insert": "metactical.barcode_generator.generate",
		"validate": "metactical.barcode_generator.po_validate",
	},
	"Material Request": {
		"before_save": "metactical.custom_scripts.material_request.material_request.before_save",
		"on_submit": "metactical.custom_scripts.material_request.material_request.on_submit",
	},
	"Address": {
		"validate": "metactical.custom_scripts.address.address.validate"
	},
	"Contact": {
		"validate": "metactical.custom_scripts.contact.contact.validate"
	},
	'''"Shipment": {
		"validate": "metactical.custom_scripts.shipment.shipment.validate",
		"before_cancel": "metactical.custom_scripts.shipment.shipment.before_cancel",
	},'''
	"Task": {
		"before_insert": "metactical.custom_scripts.task.task.set_start_date"
	}, 
	"Project": {
		"on_update": "metactical.custom_scripts.project.project.on_update"
	},
	"Item Price": {
		"validate": "metactical.custom_scripts.item_price.item_price.on_validate"
	},
	# "RabbitMQ Config": {
	# 	"on_update": "metactical.custom_scripts.rabbitmq.integration.config_change_handler"
	# }, 
	"Stock Ledger Entry": {
		"on_update": "metactical.metactical.doctype.item_inventory_output.item_inventory_output.on_sle_update",
	},
	"Payment Entry": {
		"before_insert": "metactical.custom_scripts.payment_entry.payment_entry.before_insert"
	}
}

# DocType Class
# ---------------
# Override standard doctype classes

override_doctype_class = {
	"Sales Invoice": "metactical.custom_scripts.sales_invoice.sales_invoice.CustomSalesInvoice",
	"Pick List": "metactical.custom_scripts.pick_list.pick_list.CustomPickList",
	"Quotation": "metactical.custom_scripts.quotation.quotation.CustomQuotation",
	"Sales Order": "metactical.custom_scripts.sales_order.sales_order.SalesOrderCustom",
	"Packing Slip": "metactical.custom_scripts.packing_slip.packing_slip.CustomPackingSlip",
	"Stock Reconciliation": "metactical.custom_scripts.stock_reconciliation.stock_reconciliation.CustomStockReconciliation",
	"Purchase Order": "metactical.custom_scripts.purchase_order.purchase_order.CustomPurchaseOrder",
	"Purchase Receipt": "metactical.custom_scripts.purchase_receipt.purchase_receipt.CustomPurchaseReceipt",
	"Purchase Invoice": "metactical.custom_scripts.purchase_invoice.purchase_invoice.CustomPurchaseInvoice",
	"Stock Entry": "metactical.custom_scripts.stock_entry.stock_entry.CustomStockEntry",
	"Delivery Note": "metactical.custom_scripts.delivery_note.delivery_note.DeliveryNoteCustom",
	"Company": "metactical.custom_scripts.company.company.CustomCompany",
	"Auto Email Report": "metactical.custom_scripts.auto_email_report.auto_email_report.CustomAutoEmailReport",
	"Shipment": "metactical.custom_scripts.shipment.shipment.CustomShipment",
	"Prepared Report": "metactical.custom_scripts.prepared_report.prepared_report.CustomPreparedReport",
	"Website Item": "metactical.custom_scripts.website_item.website_item.CustomWebsiteItem",
	"Item": "metactical.custom_scripts.item.item.CustomItem"
}

# Scheduled Tasks
# ---------------

scheduler_events = {
# 	"all": [
# 		"metactical.tasks.all"
# 	],
#	"all": [
#     "metactical.custom_scripts.rabbitmq.integration.subscribe_to_rabbitmq"
#	],
	"daily": [
		"metactical.reserved_calculation.recalculate_reserved_qty",
		# "metactical.custom_scripts.email_campaign.email_campaign.send_email_to_leads_or_contacts"
	],
#	"hourly": [
#		"metactical.api.shipstation.sync_shipping_status"
#	],
# 	"weekly": [
# 		"metactical.tasks.weekly"
# 	]
# 	"monthly": [
# 		"metactical.tasks.monthly"
# 	],
	"cron": {
		"15 * * * *": [
			"metactical.custom_scripts.frappe.document.clear_queued_docs",
			"metactical.custom_scripts.usaepay.usaepay_api.process_missed_usaepay_transactions",
		], "*/1 * * * *": [
			"metactical.metactical.doctype.failed_inventory_output.failed_inventory_output.process_failed_inventory_outputs"
		]
	}
}

# Testing
# -------

# before_tests = "metactical.install.before_tests"

# Migrating
after_migrate = "metactical.migrate.after_migrate"

# Overriding Methods
# ------------------------------
#
override_whitelisted_methods = {
	"erpnext.selling.doctype.sales_order.sales_order.create_pick_list": "metactical.custom_scripts.pick_list.pick_list.create_pick_list",
	"frappe.utils.print_format.download_pdf": "metactical.print_format.download_pdf",
	"erpnext.stock.doctype.pick_list.pick_list.create_delivery_note": "metactical.custom_scripts.pick_list.pick_list.create_delivery_note",
	"erpnext.stock.get_item_details.get_item_details": "metactical.custom_scripts.get_item_details.get_item_details",
	"erpnext.selling.doctype.sales_order.sales_order.make_sales_invoice": "metactical.custom_scripts.sales_order.sales_order.make_sales_invoice",
	"erpnext.selling.doctype.sales_order.sales_order.update_status": "metactical.custom_scripts.sales_order.sales_order.update_status",
	"erpnext.stock.doctype.pick_list.pick_list.PickList.set_item_locations": "metactical.custom_scripts.pick_list.pick_list.CustomPickList.set_item_locations",
	"frappe.desk.doctype.tag.tag.add_tag": "metactical.custom_scripts.tag.tag.add_tag",
	"frappe.desk.doctype.tag.tag.remove_tag": "metactical.custom_scripts.tag.tag.remove_tag",
	"frappe.core.doctype.scheduled_job_type.scheduled_job_type.execute_event": "metactical.custom_scripts.scheduled_job_type.scheduled_job_type.execute_event",
	"frappe.model.rename_doc.update_document_title": "metactical.utils.rename_doc.update_document_title"
}
#
# each overriding function accepts a `data` argument;
# generated from the base implementation of the doctype dashboard,
# along with any modifications made in other Frappe apps
#override_doctype_dashboards = {
 	#"Task": "metactical.task.get_dashboard_data"
#}

#Fixtures
fixtures = [{
		"dt": "Custom Field",
		"filters": [["name", "in", [
			'Sales Invoice-section_esr',
			'Sales Invoice-esr_reference',
			'Sales Invoice-column_esr',
			'Sales Invoice-esr_code',
			'Deleted Document-github_sync_id',
			'Tax Rule-ifw_territory',
			'Account-ifw_description',
			'POS Profile-ifw_shortage_margin',
			'POS Profile User-ifw_short_account',
			'POS Profile-ifw_auto_insert_after_scan',
			'Item-ifw_retailskusuffix',
			'POS Profile-ifw_suffix',
			'Address-tax_category',
			'Event-gcalendar_sync_id',
			'Deleted Document-gcalendar_sync_id',
			'Item-hub_sync_id',
			'Deleted Document-hub_sync_id',
			'Item-ifw_ismiscitem',
			'POS Profile-ifw_return_warehouse',
			'Sales Invoice-ifw_old_reference',
			'Payment Entry-ifw_sodraftref',
			'POS Profile-ifw_drawerfilepath',
			'POS Profile-ifw_header1',
			'POS Profile-ifw_footer',
			'POS Profile-ifw_header2'
			'POS Profile-ifw_barcode_scanner_settings',
			'POS Profile-ifw_configure_it_easily_from_posnext_',
			'POS Profile-ifw_pagewidth',
			'POS Profile-ifw_leftmargin',
			'POS Profile-ifw_rightmargin',
			'POS Profile-ifw_topmargin',
			'POS Profile-ifw_bottommargin',
			'POS Profile-ifw_usereportsetting',
			'POS Profile-ifw_usedeviceinfo',
			'POS Profile-ifw_prefix',
			'POS Profile-ifw_submitpricesfrompos',
			'Sales Invoice-payment_reminder_level',
			'Sales Invoice-exclude_from_payment_reminder_until',
			'Sales Invoice-is_proposed',
			'Sales Invoice-exported_to_abacus',
			'Sales Invoice-ifw_qtysync_ref',
			'Purchase Invoice-ifw_sereference',
			'Stock Entry-ifw_sereference',
			'Stock Reconciliation-ifw_qtysync_ref',
			'Contact-is_billing_contact',
			'POS Profile-ifw_autoopenningblnc',
			'Payment Entry-ifwsalesreturnref',
			'Payment Entry-ifw_journalentryref',
			'Stock Reconciliation-ifw_is_auto_created',
			'Sales Invoice-ifw_is_store_credit',
			'Item-ifw_section_posnext',
			'Stock Entry Detail-ifw_retailskusuffix',
			'Purchase Order Item-barcode',
			'Purchase Invoice Item-ifw_retailskusuffix',
			'Purchase Invoice Item-barcode',
			'Purchase Order-ifw_shippingnotes',
			'Item-ifw_location',
			'POS Profile-ifw_email_domain',
			'POS Profile-_ifw_email_group',
			'POS Profile-ifw_discount_alert_percent',
			'POS Profile User-ifw_max_discount_percent',
			'Pick List-date',
			'Pick List-order_type',
			'Pick List-po_no',
			'Pick List-po_date',
			'Pick List-ifw_old_reference',
			'Pick List Item-column_break_24',
			'Pick List Item-retailskusuffix',
			'Pick List Item-ifw_location',
			'Purchase Order-transporter',
			'Purchase Order-eta_date',
			'Purchase Order-column_break_33',
			'Purchase Order-carrier_used',
			'Purchase Order-tracking_id',
			'Purchase Invoice Item-ifw_location',
			'Material Request Item-default_supplier',
			'Purchase Order Item-ifw_retailskusuffix',
			'Purchase Order Item-ifw_location',
			'Sales Order-is_rush',
			'Pick List-is_rush',
			'Pick List-rush',
			'Sales Order-pl_text',
			'Pick List-pl_text',
			'Purchase Receipt Item-ifw_retailskusuffix',
			'Purchase Receipt Item-ifw_location',
			'Purchase Invoice Item-ifw_supplier_part_no',
			'Item-gpdeta_date',
			'Item-gpdorder_status',
			'Sales Invoice Item-ifw_retailskusuffix',
			'Sales Invoice Item-ifw_location',
			'Lead Source-ifw_mapping_val',
			'Packing Slip-item_barcode',
			'Packing Slip Item-scanned_qty',
			'Sales Order-ifw_signifyd_approved',
			'Sales Order-ifw_online_order_comments',
			'Purchase Order-drop_ship_notes',
			'Purchase Order-customer_address',
			'Stock Entry-track_reprint',
			'Purchase Receipt-purchase_order',
			'Item-ifw_duty_rate',
			'Item-ifw_discontinued',
			'Item-ifw_product_name_ci',
			'Item-ifw_item_notes',
			'Item-ifw_po_notes',
			'Item Supplier-ifw_supplier_qoh',
			'Pick List-barcode',
			'Pick List-tracking_print_status',
			'Pick List-print_date_time',
			'Pick List-track_print_user',
			'Lead Source-ifw_website_id',
			'Mode of Payment-ifw_mapping_values',
			'Customer-mobile',
			'Customer-email',
			'Item-ifw_item_notes2',
			'Sales Invoice-outstanding_balance',
			'Pick List-cancel_information',
			'Pick List-cancel_reason',
			'Pick List-column_break_27',
			'Pick List-notes',
			'Price List-ifw_website_id',
			'Sales Order-ifw_old_reference',
			'Sales Order Item-ifw_retailskusuffix',
			'Sales Order Item-ifw_location',
			'Sales Order-cancel_information',
			'Sales Order-cancel_reason',
			'Address-ifw_first_name',
			'Address-ifw_last_name',
			'Item Supplier-ifw_sqohtimestamp',
			'Pick List-pick_list_cancel_date',
			'Sales Order-ifw_signifyd_properties',
			'Sales Order-ifw_signifyd_sid',
			'Sales Order-ifw_signifyd_caseid',
			'Sales Order-ifw_signifyd_casestatus',
			'Sales Order-ifw_signifyd_column_break',
			'Sales Order-ifw_signifyd_score',
			'Sales Order-ifw_signifyd_guaranteedisposition',
			'Sales Order-ifw_signifyd_fulfilled',
			'Stock Entry-sales_order_no',
			'Stock Entry Detail-sales_order_item',
			'Stock Entry Detail-sales_order',
			'Sales Order-ais_payment_notes',
			'Pick List-reprinted',
			'Sales Order-pick_list_submitted_date',
			'Sales Order-ifw_store_pickup',
			'Stock Entry Detail-sal_trackinginfo',
			'Stock Entry Detail-sal_warehouseshipdate',
			'Stock Entry-sal_trackinginfo',
			'Stock Entry-sal_warehouseshipdate',
			'Company-ais_gst_tps_no',
			'Company-ais_pst_no',
			'Sales Invoice-ais_barcode',
			'Pick List-sal_flag_qty',
			'Pick List-sal__flagged_item',
			'Journal Entry-ais_sales_order',
			'Address-ifw_website_id',
			'Sales Order Item-sal_reserved_qty',
			'Tax Rule-ifw_shopping_cart_hint',
			'Sales Order Item-ais_is_stock_item',
			'POS Profile User-ifw_is_main_pos_user',
			'POS Profile User-ifw_include_in_close',
			'POS Profile-ifw_email_group',
			'Email Domain-ifw_password',
			'Address-ais_gst_no',
			'Item-asi_item_class',
			'Delivery Note-ais_shipment_cost',
			'Delivery Note-ais_package_weight',
			'Delivery Note-ais_package_size',
			'Stock Entry-received_from_stock',
			'Delivery Note-ais_shipstation_orderid',
			'POS Profile User-ifw_allow_to_edit_rate',
			'Delivery Note-ais_updated_by_shipstation',
			'Pick List-sal_sto_barcode',
			'Auto Repeat-auto_repeat',
			'Prepared Report-auto_repeat',
			'Delivery Note-ais_section_shipstation_information',
			'Delivery Note-ais_shipstation_order_ids',
			'Purchase Order-ais_cancel_date',
			'Sales Order Item-ifw_specifications',
			'Sales Order Item-ifw_cb1',
			'Pick List-ais_source',
			'Payment Entry-ais_pos_profile',
			'Item-ais_month_cover',
			'Customer-ais_company',
			'Address-ais_company',
			'Stock Reconciliation-ais_cycle_count',
			'Employee-ais_akno',
			'Employee-ais_isot',
			'Employee-ais_isstudent',
			'Stock Entry-ais_submitted_date',
			'Stock Entry-ais_ste_text',
			'Employee-ais_sin_no',
			'Employee-ais_sin_expiry',
			'Employee-ais_issalary',
			'Employee-ais_adp_no',
			'Employee-ais_bank_transit',
			'Employee-ais_bank_institution',
			'Item-ais_poreorderlevel',
			'Item-ais_poreorderqty',
			'Stock Entry-ais_courier_name',
			'Sales Invoice-ais_automated_creation',
			'Customer-ifw_posprofile',
			'Customer-ifw_signup_fornewsletter',
			'Sales Invoice-transporter_address',
			'Sales Invoice-transporter_address_display',
			'Supplier-irs_1099',
			'Sales Order-exempt_from_sales_tax',
			'Sales Invoice-exempt_from_sales_tax',
			'Customer-exempt_from_sales_tax',
			'Quotation-exempt_from_sales_tax',
			'Purchase Invoice-invoice_copy',
			'Purchase Invoice-reverse_charge',
			'Purchase Invoice-reason_for_issuing_document',
			'Purchase Invoice-eligibility_for_itc',
			'Purchase Invoice-itc_cess_amount',
			'Purchase Invoice-place_of_supply',
			'Purchase Order-place_of_supply',
			'Purchase Receipt-place_of_supply',
			'Delivery Note-place_of_supply',
			'Delivery Note-distance',
			'Delivery Note-mode_of_transport',
			'Delivery Note-ewaybill',
			'Delivery Note-port_code',
			'Delivery Note-shipping_bill_number',
			'Delivery Note-shipping_bill_date',
			'Journal Entry-reversal_type',
			'Journal Entry-company_address',
			'Sales Order-place_of_supply',
			'Quotation Item-is_nil_exempt',
			'Supplier Quotation Item-is_nil_exempt',
			'Sales Order Item-is_nil_exempt',
			'Delivery Note Item-is_nil_exempt',
			'Sales Invoice Item-is_nil_exempt',
			'Sales Invoice Item-taxable_value',
			'Purchase Order Item-is_nil_exempt',
			'Purchase Receipt Item-is_nil_exempt',
			'Purchase Invoice Item-is_nil_exempt',
			'Purchase Invoice Item-taxable_value',
			'Material Request Item-is_nil_exempt',
			'Employee-ifsc_code',
			'Employee-pan_number',
			'Employee-micr_code',
			'Employee-provident_fund_account',
			'Customer-gst_category',
			'Party Account-debtor_creditor_number',
			'Payment Entry-company_address',
			'Payment Entry-place_of_supply',
			'Payment Entry-customer_address',
			'Customer-export_type',
			'Supplier-export_type',
			'POS Invoice-place_of_supply',
			'POS Invoice Item-is_nil_exempt',
			'POS Invoice Item-taxable_value',
			'Finance Book-for_income_tax',
			'Sales Invoice-invoice_copy',
			'Sales Invoice-reverse_charge',
			'Sales Invoice-reason_for_issuing_document',
			'Sales Invoice-port_code',
			'Sales Invoice-shipping_bill_number',
			'Sales Invoice-shipping_bill_date',
			'Sales Invoice-place_of_supply',
			'Sales Invoice-transporter_info',
			'Sales Invoice-transporter',
			'Sales Invoice-ewaybill',
			'Sales Invoice-irn',
			'Sales Invoice-irn_cancelled',
			'Sales Invoice-eway_bill_validity',
			'Sales Invoice-ack_no',
			'Sales Invoice-ack_date',
			'Sales Invoice-irn_cancel_date',
			'Sales Invoice-signed_einvoice',
			'Sales Invoice-signed_qr_code',
			'Sales Invoice-qrcode_image',
			'Sales Invoice-einvoice_status',
			'Sales Invoice-failure_description',
			'Tax Category-is_inter_state',
			'Tax Category-is_reverse_charge',
			'Tax Category-tax_category_column_break',
			'Quotation-place_of_supply',
			'POS Profile-ifw_dropboxaccesstoken',
			'POS Profile-ifw_destinationfolderpath',
			'POS Profile-ifw_uploadtodropbox',
			'POS Profile-ifw_clientid',
			'POS Profile-ifw_clientsecret',
			'POS Profile-ifw_username',
			'POS Profile-ifw_uploadtoonedrive',
			'POS Profile-ifw_tenantid',
			'Sales Order-ais_close_reason',
			'Sales Order-column_break_161',
			'Sales Invoice-eway_bill_cancelled',
			'Item-is_nil_exempt',
			'Sales Invoice-driver',
			'Sales Invoice-lr_no',
			'Sales Invoice-vehicle_no',
			'Sales Invoice-distance',
			'Sales Invoice-transporter_col_break',
			'Sales Invoice-transporter_name',
			'Sales Invoice-mode_of_transport',
			'Sales Invoice-driver_name',
			'Sales Invoice-lr_date',
			'Sales Invoice-einvoice_section',
			'Print Settings-print_uom_after_quantity',
			'Stock Reconciliation-ais_cycle_count_v2',
			'Item-column_break_134',
			'POS Profile-ifw_auto_reconcile_oos_items',
			'Stock Entry-branch',
			'Purchase Order Item-branch',
			'Purchase Receipt Item-branch',
			'Stock Entry Detail-branch',
			'Purchase Taxes and Charges-branch',
			'Purchase Order-ais_scan_to_confirm',
			'Purchase Receipt-ais_scan_to_confirm',
			'Stock Entry-ais_scan_to_confirm',
			'Employee-ais_isotherfile',
			'Employee-ais_customnotes',
			'Delivery Note-ais_temp_pick_list',
			'Sales Invoice-branch',
			'Purchase Invoice-branch',
			'Delivery Note-branch',
			'Stock Reconciliation-branch',
			'Quotation-ais_barcode',
			'Sales Invoice-ifw_notes',
			'Employee-ais_state',
			'Stock Reconciliation-ais_queue_failed',
			'Purchase Order-ais_queue_failed',
			'Purchase Receipt-ais_queue_failed',
			'Purchase Invoice-ais_queue_failed',
			'Stock Reconciliation-ais_queue_status',
			'Purchase Order-ais_queue_status',
			'Purchase Invoice-ais_queue_status',
			'Purchase Receipt-ais_queue_status',
			'Stock Settings-ais_sales_report_settings',
			'Stock Settings-ais_default_price_list',
			'Purchase Order-ais_queued_date',
			'Stock Reconciliation-ais_queued_date',
			'Purchase Invoice-ais_queued_date',
			'Purchase Receipt-ais_queued_date',
			'Purchase Receipt-ais_background_section',
			'Purchase Receipt-ais_queued_by',
			'Purchase Receipt-column_break_136',
			'Purchase Receipt-ais_queueu_comment',
			'Purchase Order-ais_background_section',
			'Purchase Order-ais_queueu_comment',
			'Purchase Order-column_break_148',
			'Purchase Order-ais_queued_by',
			'Purchase Invoice-ais_background_section',
			'Purchase Invoice-ais_queueu_comment',
			'Purchase Invoice-column_break_185',
			'Purchase Invoice-ais_queued_by',
			'Stock Reconciliation-ais_background_section',	
			'Stock Reconciliation-ais_queueu_comment',
			'Stock Reconciliation-column_break_26',
			'Stock Reconciliation-ais_queued_by',
			'Stock Reconciliation-ais_reason_for_adjustment',
			'POS Profile User-ifw_allow_to_edit_rate_increase_only',
			'Shipment-carrier_status',
			'Shipment-po_number',
			'POS Profile-ifw_default_lead_source',
			'Shipment-other_reason',
			'Shipment-multiple_shipment',
			'Shipment-shipments',
			'Shipment-output_format',
			'Stock Entry-ais_ste_barcode',
			'Stock Entry-ais_from_report',
			'Lead Source-ais_report_label',
			'Address-company',
			'Shipment-warehouse',
			'Warehouse-country',
			'Stock Entry Detail-ais_target_qoh',
			'Purchase Invoice-company_trn',
			'Purchase Invoice-recoverable_standard_rated_expenses',
			'Purchase Invoice-recoverable_reverse_charge',
			'Purchase Invoice-vat_section',
			'Purchase Invoice-permit_no',
			'Purchase Order-company_trn',
			'Purchase Order-recoverable_standard_rated_expenses',
			'Purchase Order-reverse_charge',
			'Purchase Order-recoverable_reverse_charge',
			'Purchase Order-vat_section',
			'Purchase Order-permit_no',
			'Purchase Receipt-company_trn',
			'Purchase Receipt-recoverable_standard_rated_expenses',
			'Purchase Receipt-reverse_charge',
			'Purchase Receipt-recoverable_reverse_charge',
			'Purchase Receipt-vat_section',
			'Purchase Receipt-permit_no',
			'Sales Invoice-company_trn',
			'Sales Invoice-tourist_tax_return',
			'Sales Invoice-vat_section',
			'Sales Invoice-permit_no',
			'Sales Order-company_trn',
			'Sales Order-tourist_tax_return',
			'Sales Order-vat_section',
			'Sales Order-permit_no',
			'Delivery Note-company_trn',
			'Delivery Note-tourist_tax_return',
			'Delivery Note-vat_section',
			'Delivery Note-permit_no',
			'Sales Order Item-tax_rate',
			'Sales Order Item-tax_amount',
			'Sales Order Item-total_amount',
			'Purchase Order Item-tax_rate',
			'Purchase Order Item-tax_amount',
			'Purchase Order Item-total_amount',
			'Purchase Receipt Item-tax_rate',
			'Purchase Receipt Item-tax_amount',
			'Purchase Receipt Item-total_amount',
			'Delivery Note-ais_skip_auto_invoice',
			'Item-ais_blockfrmstoresale',
			'Material Request-ais_suppliers',
			'POS Profile User-ifw_can_return_without_invoice',
			'POS Profile-ifw_end_of_day_closing_account',
			'Lead Source-custom_lead_source_id',
			'Lead Source-custom_lead_source_count',
			'Lead Source-custom_lead_source_domain',
			'Purchase Invoice-export_type',
			'Pick List-do_not_create_delivery',
			'Project-github_sync_id',
			'Task-github_sync_id',
			'Task-checklists_html',
			'Task-section_break_kqv1a',
			'Task-checklists',
			'Employee-bank_document',
			'Shipment Delivery Note-source',
			'Shipment Delivery Note-order_id',
			'Shipment-ais_shipment_status',
			'Shipment-neb_source',
			'Shipment-neb_customer_po_number',
			'Shipment Delivery Note-neb_source',
			'Shipment Delivery Note-neb_order_id',
			'Sales Invoice-ais_background_section',
			'Sales Order-ais_background_section',
			'Sales Order-ais_queue_status',
			'Sales Order-ais_queueu_comment',
			'Sales Order-column_break_ja7qr',
			'Sales Order-ais_queued_date',
			'Sales Order-ais_queued_by',
			'Sales Invoice-ais_queue_status',
			'Sales Invoice-ais_queueu_comment',
			'Sales Invoice-column_break_hfm1c',
			'Sales Invoice-ais_queued_date',
			'Sales Invoice-ais_queued_by',
			'Delivery Note-ais_background_section',
			'Delivery Note-ais_queue_status',
			'Delivery Note-column_break_ccxkz',
			'Delivery Note-ais_queued_date',
			'Delivery Note-ais_queued_by',
			'Supplier-tax_code',
			'Delivery Note-ais_queueu_comment',
			'Item-is_zero_rated',
			'Item-is_exempt',
			'Address-emirate',
			'Shipment-shipstation_information',
			'Supplier-lead_time_in_days',
			'Sales Invoice-neb_return_against',
			'Shipment-ais_shipstation_transporter',
			'Shipment-ais_shipstation_weight_uom',
			'Shipment-column_break_2xjwt',
			'Shipment-ais_shipstation_receipt_no',
			'Shipment-ais_shipstation_receipt_date',
			'Shipment-ais_shipstation_dimensions_uom',
			'Purchase Invoice-itc_integrated_tax',
			'Purchase Invoice-itc_central_tax',
			'Purchase Invoice-itc_state_tax',
			'Sales Order-mena_is_cp_verified',
			'Sales Invoice-mena_is_cp_verified',
			'Delivery Note-mena_is_cp_verified',
			'Shipment-mena_is_cp_verified',
			'Stock Entry Detail-ifw_location',
			'Sales Invoice-neb_pay_with_store_credit',
			'Sales Invoice-neb_store_credit_beneficiary',
			'Sales Order-usaepay',
			'Sales Order-neb_usaepay_transaction_key',
			'Sales Invoice-ifw_retailskusuffix',
			'Sales Invoice-sal_trackinginfo',
			'Sales Invoice-sal_warehouseshipdate',
			'Sales Invoice-target_qoh',
			'Sales Invoice-location',
			'Sales Order-ais_queue_failed',
			'Delivery Note-ais_queue_failed',
			'Sales Invoice-ais_queue_failed',
			'Sales Order-neb_payment_completed_at',
			'Sales Invoice-neb_payment_completed_at',
			'Item Price-ifw_retailskusuffix',
			'Address-mena_is_cp_verified',
			'Material Request Item-ais_default_supplier',
			'Material Request Item-ifw_location',
			'Item-ais_shipping_section',
			'Item-ais_shipping_height',
			'Item-ais_shipping_width',
			'Item-ais_shipping_length',
			'Item-column_break_00fzl',
			'Item-column_break_nh4zp',
			'Pick List-ais_background_queue',
			'Pick List-ais_queue_failed',
			'Pick List-ais_queue_status',
			'Pick List-ais_queueu_comment',
			'Pick List-column_break_7wazs',
			'Pick List-ais_queued_date',
			'Pick List-ais_queued_by',
			'Shipment-column_break_5cimu',
			'Pricing Rule-ifw_retailskusuffix',
			'Material Request Item-qoh',
			'Lead Source-custom_neb_sb_warehouse_inventory_sync',
			'Item-custom_neb_website_deduct_qty',
			'Packing Slip-custom_neb_box_height',
			'Packing Slip-custom_neb_box_width',
			'Packing Slip-custom_neb_parcel_template',
			'Packing Slip-custom_neb_box_length',
			'Shipment Parcel-custom_neb_box',
			'Shipment Parcel-custom_neb_delivery_note',
			'Employee-employment_type',
			'Employee-job_applicant',
			'Employee-grade',
			'Employee-default_shift',
			'Employee-health_insurance_section',
			'Employee-health_insurance_provider',
			'Employee-health_insurance_no',
			'Employee-approvers_section',
			'Employee-expense_approver',
			'Employee-leave_approver',
			'Employee-column_break_45',
			'Employee-shift_request_approver',
			'Employee-salary_cb',
			'Employee-payroll_cost_center',
			'Company-hr_settings_section',
			'Company-default_expense_claim_payable_account',
			'Company-default_employee_advance_account',
			'Company-column_break_10',
			'Company-default_payroll_payable_account',
			'Department-section_break_4',
			'Department-payroll_cost_center',
			'Department-column_break_9',
			'Department-leave_block_list',
			'Department-approvers',
			'Department-shift_request_approver',
			'Department-leave_approvers',
			'Department-expense_approvers',
			'Designation-appraisal_template',
			'Designation-required_skills_section',
			'Designation-skills',
			'Project-total_expense_claim',
			'Task-total_expense_claim',
			'Timesheet-salary_slip',
			'Terms and Conditions-hr',
			'Lead Source-custom_neb_price_list',
			'Item-neb_website_specifications',
			'Item Group-neb_website_specifications',
			'Item-neb_copy_from_item_group',
			'Website Item-neb_website_specifications',
			'Item-neb_variantavailabilityrule',
			'Pick List-ais_picked_by',
			'POS Profile User-column_break_vcps1',
			'POS Profile User-neb_pin',
			'Item-custom_ais_related_sku',
			'Shipment-custom_ais_require_signature',
			'Shipment-custom_ais_do_not_safe_drop',
			'Item Attribute-sort_order',
			'Item Attribute Value-sort_order',
			'Pricing Rule-publish',
			'Address-custom_ais_address_verified',
			'Sales Order-custom_ais_address_verified',
			'POS Profile User-neb_send_welcome_email',
			'Coupon Code-custom_sales_invoice',
			'Contact-custom_ais_contactnotes',
			'Lead Source-neb_default_warehouse',
			'Lead Source-neb_company',
			'Shipment-custom_dangerous_goods',
			'Shipment-custom_dangerous_goods_class',
			'Shipment-custom_dangerous_goods_mode',
			"Lead Source-neb_company_address",
   			'Item-sb_tag',
			"Shipment-custom_nondelivery_handling_option",
			"Shipment-neb_notification_email_sent",
			"Purchase Receipt Item-custom_neb_comment",
			"Sales Invoice-neb_return_document",
			"Shipment Parcel Template-custom_disabled",
			"Item-reorder_months",
			"Item-months_to_reorder",
			"Sub Operation-time_in_secs",
			"BOM Operation-time_in_secs",
			"BOM Item-supplier",
			"BOM-total_operation_time",
			"BOM-operation_time",
			"BOM-output_per_day",
			"BOM-no_of_workers",
			"BOM-sample_details",
			"BOM-retail_sku",
			"BOM-sub_operations",
			'Item-item_detail',
			"Item-request_ai_suggestion",
			"Item-slugs_and_descriptions",
			"Item-neb_paypal_restricted",
			"Item-neb_airship_restricted",
			"Employee-short_code",
			"Item-last_pinged_on",
			"POS Profile-auto_logout_after_transaction",
			"Sales Invoice Item-sales_person",
			"Sales Order Item-sales_person",
			"POS Profile User-allow_flat_rate",
			"Item-is_published",
			"Item Attribute Value-hide_when_out_of_stock",
			"Pricing Rule-min_qty_to_stop_discount",
			"POS Profile-neb_manual_orders_tag",
			"Lead Source-neb_country",
			"Item-display_weight",
			"Stock Entry Detail-custom_ais_active_qoh",
			"POS Profile-neb_allow_manual_order",
			"Address-neb_mobile_not_formatted"
		]]]
	},
	{
		"dt": "Property Setter",
		"filters": [["name", "in", [
			"Customer-naming_series-options",
			"Purchase Order-naming_series-options",
			"Item Group-website_specifications-hidden",
			"Item Group-main-field_order",
			"Pick List Item-main-field_order",
			"Pick List Item-serial_no-depends_on",
			"Pick List Item-warehouse-read_only",
			"Item Attribute Value-main-field_order",
			"Item Price-main-autoname",
			"Item Price-price_list-in_list_view",
			"Item Price-brand-in_list_view",
			"Item Price-reference-in_list_view",
			"Item Price-reference-in_standard_filter",
			"Stock Entry-main-links_order",
			"Stock Entry-sal_warehouseshipdate-in_list_view",
			"Stock Entry-sal_trackinginfo-in_list_view",
			"Stock Entry-ais_courier_name-in_list_view",
			"Stock Entry-to_warehouse-in_list_view",
			"Stock Entry-posting_date-in_list_view",
			"Stock Entry-from_warehouse-in_list_view",
			"Stock Entry-main-default_print_format",
			"Stock Entry-posting_date-in_standard_filter",
			"Stock Entry-stock_entry_type-in_standard_filter",
			"Stock Entry-main-search_fields",
			"Stock Entry-main-title_field",
			"Stock Entry-per_transferred-in_list_view",
			"Stock Entry-purpose-in_list_view",
			"Stock Entry-stock_entry_type-in_list_view",
			"Stock Entry-scan_barcode-hidden",
			"Stock Entry-stock_entry_type-default",
			"Stock Entry-naming_series-options",
			"Task-duration-hidden",
			"Task-issue-hidden",
			"Task-type-hidden",
			"Task-color-hidden",
			"Task-is_group-hidden",
			"Task-is_template-hidden",
			"Task-task_weight-hidden",
			"Task-parent_task-hidden",
			"Task-expected_time-hidden",
			"Task-is_milestone-hidden",
			"Task-sb_costing-hidden",
			"Task-sb_more_info-hidden",
			"Task-sb_depends_on-hidden",
			"Task-total_billing_amount-hidden",
			"Task-sb_actual-hidden",
			"Task-priority-hidden",
			"Task-progress-hidden",
			"Task-project-in_list_view",
			"Task-is_group-in_list_view",
			"Task-priority-in_list_view",
			"Task-exp_start_date-label",
			"Task-is_milestone-in_list_view",
			"Task-description-in_list_view",
			"Task-exp_end_date-label",
			"Task-exp_end_date-in_list_view",
			"Task-exp_start_date-in_list_view",
			"Delivery Note-pick_list-hidden",
			"Delivery Note-main-search_fields",
			"Delivery Note-naming_series-options",
			"Delivery Note-title-in_list_view",
			"Delivery Note-grand_total-in_list_view",
			"Delivery Note-per_installed-in_list_view",
			"Delivery Note-scan_barcode-hidden",
			"Delivery Note-tax_id-hidden",
			"Delivery Note-tax_id-print_hide",
			"Delivery Note-base_rounded_total-hidden",
			"Delivery Note-base_rounded_total-print_hide",
			"Delivery Note-rounded_total-hidden",
			"Delivery Note-rounded_total-print_hide",
			"Delivery Note-disable_rounded_total-default",
			"Delivery Note-in_words-hidden",
			"Delivery Note-in_words-print_hide",
			"Delivery Note-main-field_order",
			"Delivery Note-ais_queue_status-no_copy",
			"Delivery Note-ais_queueu_comment-no_copy",
			"Delivery Note-ais_queue_failed-no_copy",
			"Delivery Note-ais_queued_date-no_copy",
			"Delivery Note-ais_queued_by-no_copy",
			"Purchase Receipt-scan_barcode-hidden",
			"Purchase Receipt-purchase_order-read_only",
			"Purchase Receipt-naming_series-options",
			"Purchase Receipt-main-field_order",
			"Purchase Receipt-main-default_print_format",
			"Purchase Receipt-in_words-print_hide",
			"Purchase Receipt-in_words-hidden",
			"Purchase Receipt-ais_queueu_comment-allow_on_submit",
			"Purchase Receipt-ais_queued_date-allow_on_submit",
			"Purchase Receipt-ais_queued_by-allow_on_submit",
			"Purchase Receipt-ais_queue_status-allow_on_submit",
			"Purchase Receipt-ais_queue_failed-allow_on_submit",
			"Address-phone-label",
			"Address-address_type-options",
			"Address-phone-description",
			"Address-address_line1-translatable",
			"Address-address_line2-translatable",
			"Address-main-field_order",
			"Pick List-status-allow_on_submit",
			"Pick List-main-field_order",
			"Pick List-ais_queue_status-no_copy",
			"Pick List-ais_queue_status-default",
			"Pick List-ais_queue_failed-no_copy",
			"Pick List-ais_queueu_comment-no_copy",
			"Pick List-ais_queued_date-no_copy",
			"Pick List-ais_queued_by-no_copy",
			"Pick List-naming_series-options",
			"Pick List-main-default_print_format",
			"Pick List-get_item_locations-hidden",
			"Pick List-parent_warehouse-read_only",
			"Pick List-status-options",
			"Sales Invoice-title-in_list_view",
			"Sales Invoice-tax_id-print_hide",
			"Sales Invoice-tax_id-hidden",
			"Sales Invoice-scan_barcode-hidden",
			"Sales Invoice-rounded_total-print_hide",
			"Sales Invoice-rounded_total-hidden",
			"Sales Invoice-po_no-label",
			"Sales Invoice-payment_schedule-print_hide",
			"Sales Invoice-naming_series-options",
			"Sales Invoice-main-field_order",
			"Sales Invoice-main-default_print_format",
			"Sales Invoice-in_words-print_hide",
			"Sales Invoice-in_words-hidden",
			"Sales Invoice-ignore_pricing_rule-default",
			"Sales Invoice-ifw_old_reference-in_list_view",
			"Sales Invoice-grand_total-in_list_view",
			"Sales Invoice-due_date-print_hide",
			"Sales Invoice-disable_rounded_total-default",
			"Sales Invoice-customer-in_list_view",
			"Sales Invoice-base_rounded_total-print_hide",
			"Sales Invoice-base_rounded_total-hidden",
			"Sales Invoice-additional_discount_account-mandatory_depends_on",
			"Sales Invoice-additional_discount_account-hidden",
			"Packing Slip-naming_series-options",
			"Packing Slip-main-field_order",
			"Packing Slip-gross_weight_uom-fetch_if_empty",
			"Packing Slip-gross_weight_uom-fetch_from",
			"Packing Slip-gross_weight_pkg-fetch_from",
			"Purchase Receipt Item-supplier_part_no-hidden",
			"Purchase Receipt Item-warehouse-in_list_view",
			"Purchase Receipt Item-rejected_qty-in_list_view",
			"Purchase Receipt Item-supplier_part_no-in_list_view",
			"Purchase Receipt Item-from_warehouse-hidden",
			"Purchase Receipt Item-barcode-hidden",
			"Purchase Receipt Item-purchase_order_item-hidden",
			"Purchase Receipt Item-rate-columns",
			"Purchase Receipt Item-qty-columns",
			"Purchase Receipt Item-net_amount-in_list_view",
			"Employee-naming_series-options",
			"Employee-branch-in_list_view",
			"Employee-prefered_email-in_list_view",
			"Employee-employee_number-in_list_view",
			"Employee-designation-in_list_view",
			"Employee-employee_number-in_standard_filter",
			"Employee-branch-in_standard_filter",
			"Employee-prefered_email-in_standard_filter",
			"Employee-naming_series-hidden",
			"Employee-naming_series-reqd",
			"Employee-employee_number-reqd",
			"Employee-employee_number-hidden",
			"Website Item-website_specifications-hidden",
			"Website Item-main-field_order",
			"Website Item-copy_from_item_group-hidden",
			"POS Profile User-main-field_order",
			"Item Attribute-main-field_order",
			"POS Profile-main-field_order",
			"POS Profile-main-default_print_format",
			"POS Profile-naming_series-options",
			"Payment Entry-naming_series-options",
			"Payment Entry-paid_amount-in_list_view",
			"Payment Entry-mode_of_payment-reqd",
			"Payment Entry-party_name-in_list_view",
			"Purchase Invoice-ais_queued_by-allow_on_submit",
			"Purchase Invoice-ais_queued_date-allow_on_submit",
			"Purchase Invoice-ais_queueu_comment-allow_on_submit",
			"Purchase Invoice-ais_queue_status-allow_on_submit",
			"Purchase Invoice-ais_queue_failed-allow_on_submit",
			"Purchase Invoice-scan_barcode-hidden",
			"Purchase Invoice-additional_discount_account-mandatory_depends_on",
			"Purchase Invoice-additional_discount_account-hidden",
			"Purchase Invoice-payment_schedule-print_hide",
			"Purchase Invoice-due_date-print_hide",
			"Purchase Invoice-in_words-print_hide",
			"Purchase Invoice-in_words-hidden",
			"Purchase Invoice-rounded_total-print_hide",
			"Purchase Invoice-rounded_total-hidden",
			"Purchase Invoice-base_rounded_total-print_hide",
			"Purchase Invoice-base_rounded_total-hidden",
			"Purchase Invoice-main-default_print_format",
			"Purchase Invoice-naming_series-options",
			"Supplier-supplier_name-translatable",
			"Supplier-naming_series-hidden",
			"Supplier-naming_series-reqd",
			"Supplier-pan-hidden",
			"Supplier-naming_series-options",
			"Purchase Order Item-price_list_rate-in_list_view",
			"Purchase Order Item-base_price_list_rate-in_list_view",
			"Purchase Order Item-price_list_rate-columns",
			"Purchase Order Item-discount_percentage-columns",
			"Purchase Order Item-item_name-columns",
			"Purchase Order Item-amount-columns",
			"Purchase Order Item-amount-in_list_view",
			"Purchase Order Item-discount_percentage-width",
			"Purchase Order Item-qty-width",
			"Purchase Order Item-item_name-in_list_view",
			"Purchase Order Item-item_code-columns",
			"Purchase Order Item-item_code-label",
			"Purchase Order Item-supplier_part_no-hidden",
			"Purchase Order Item-discount_percentage-label",
			"Purchase Order Item-discount_percentage-in_list_view",
			"Purchase Order Item-discount_amount-columns",
			"Purchase Order Item-schedule_date-in_list_view",
			"Purchase Order Item-rate-columns",
			"Stock Entry Detail-item_code-permlevel",
			"Stock Entry Detail-stock_uom-report_hide",
			"Stock Entry Detail-uom-report_hide",
			"Stock Entry Detail-valuation_rate-report_hide",
			"Stock Entry Detail-amount-report_hide",
			"Stock Entry Detail-item_group-print_hide",
			"Stock Entry Detail-barcode-hidden",
			"Stock Entry Detail-qty-columns",
			"Stock Entry Detail-basic_rate-in_list_view",
			"Stock Entry Detail-item_code-columns",
			"Item-defaults-collapsible",
			"Item-manufacturing-permlevel",
			"Item-item_tax_section_break-permlevel",
			"Item-deferred_revenue-permlevel",
			"Item-supplier_details-collapsible",
			"Item-purchase_details-collapsible",
			"Item-variants_section-permlevel",
			"Item-reorder_section-permlevel",
			"Item-inventory_section-permlevel",
			"Item-valuation_rate-permlevel",
			"Item-asset_naming_series-permlevel",
			"Item-asset_category-permlevel",
			"Item-auto_create_assets-permlevel",
			"Item-is_fixed_asset-permlevel",
			"Item-standard_rate-permlevel",
			"Item-opening_stock-permlevel",
			"Item-include_item_in_manufacturing-permlevel",
			"Item-is_stock_item-permlevel",
			"Item-allow_alternative_item-permlevel",
			"Item-disabled-permlevel",
			"Item-is_item_from_hub-permlevel",
			"Item-name_and_description_section-collapsible",
			"Item-description-translatable",
			"Item-item_name-translatable",
			"Item-item_code-reqd",
			"Item-item_code-hidden",
			"Item-barcode-hidden",
			"Item-naming_series-reqd",
			"Item-default_discount_account-hidden",
			"Item-manufacturing-collapsible_depends_on",
			"Item-image-hidden",
			"Item-main-sort_field",
			"Item-barcodes-hidden",
			"Item-hub_publishing_sb-hidden",
			"Item-website_section-hidden",
			"Item-inspection_criteria-hidden",
			"Item-customer_details-hidden",
			"Item-deferred_expense_section-hidden",
			"Item-hub_publishing_sb-collapsible",
			"Item-naming_series-options",
			"Item-main-field_order",
			"Shipment-delivery_address_name-label",
			"Shipment-pickup_address_name-label",
			"Shipment-shipment_type-options",
			"Shipment-description_of_content-reqd",
			"Shipment-main-field_order",
			"Stock Reconciliation Item-barcode-hidden",
			"Stock Reconciliation Item-warehouse-in_standard_filter",
			"Shipment Parcel-main-field_order",
			"Sales Order-taxes_and_charges-reqd",
			"Sales Order-tax_id-print_hide",
			"Sales Order-tax_id-hidden",
			"Sales Order-source-reqd",
			"Sales Order-section_break_48-collapsible_depends_on",
			"Sales Order-scan_barcode-hidden",
			"Sales Order-rounded_total-print_hide",
			"Sales Order-rounded_total-hidden",
			"Sales Order-po_no-label",
			"Sales Order-po_no-in_standard_filter",
			"Sales Order-po_no-in_list_view",
			"Sales Order-po_date-in_list_view",
			"Sales Order-per_delivered-in_list_view",
			"Sales Order-per_billed-in_list_view",
			"Sales Order-payment_schedule-print_hide",
			"Sales Order-naming_series-options",
			"Sales Order-more_info-collapsible_depends_on",
			"Sales Order-main-links_order",
			"Sales Order-main-field_order",
			"Sales Order-main-default_print_format",
			"Sales Order-in_words-print_hide",
			"Sales Order-in_words-hidden",
			"Sales Order-ignore_pricing_rule-default",
			"Sales Order-due_date-print_hide",
			"Sales Order-disable_rounded_total-default",
			"Sales Order-delivery_date-in_list_view",
			"Sales Order-connections_tab-label",
			"Sales Order-company_address-reqd",
			"Sales Order-base_rounded_total-print_hide",
			"Sales Order-base_rounded_total-hidden",
			"Pricing Rule-main-track_changes",
			"Pricing Rule-main-field_order",
			"Quotation-main-default_print_format",
			"Quotation-payment_schedule_section-hidden",
			"Quotation-payment_schedule_section-read_only",
			"Quotation-payment_terms_template-hidden",
			"Quotation-payment_terms_template-read_only",
			"Quotation-payment_schedule-hidden",
			"Quotation-payment_schedule-read_only",
			"Quotation-taxes_section-read_only",
			"Quotation-tax_category-read_only",
			"Quotation-base_total_taxes_and_charges-hidden",
			"Quotation-currency-default",
			"Quotation-print_settings-hidden",
			"Quotation-base_rounded_total-hidden",
			"Quotation-base_rounded_total-print_hide",
			"Quotation-rounded_total-hidden",
			"Quotation-rounded_total-print_hide",
			"Quotation-in_words-hidden",
			"Quotation-in_words-print_hide",
			"Quotation-naming_series-options",
			"Sales Order Item-delivery_date-in_list_view",
			"Sales Order Item-actual_qty-columns",
			"Sales Order Item-actual_qty-in_list_view",
			"Sales Order Item-rate-columns",
			"Project-project_type-hidden",
			"Project-is_active-hidden",
			"Project-percent_complete_method-hidden",
			"Project-expected_start_date-hidden",
			"Project-expected_end_date-hidden",
			"Project-department-hidden",
			"Project-customer_details-hidden",
			"Project-users_section-hidden",
			"Project-section_break0-hidden",
			"Project-section_break_18-hidden",
			"Project-project_details-hidden",
			"Project-margin-hidden",
			"Project-monitor_progress-hidden",
			"Project-status-hidden",
			"Project-percent_complete-hidden",
			"Project-column_break_5-hidden",
			"Project-project_template-hidden",
			"Project-priority-hidden",
			"Project-customer-hidden",
			"Project-column_break_14-hidden",
			"Project-sales_order-hidden",
			"Project-users-hidden",
			"Project-notes-hidden",
			"Project-actual_start_date-hidden",
			"Project-actual_time-hidden",
			"Project-column_break_20-hidden",
			"Project-actual_end_date-hidden",
			"Project-estimated_costing-hidden",
			"Project-project_type-in_list_view",
			"Project-expected_end_date-in_list_view",
			"Project-estimated_costing-in_list_view",
			"Project-status-in_standard_filter",
			"Project-project_name-in_list_view",
			"Customer-customer_name-translatable",
			"Customer-territory-in_standard_filter",
			"Customer-customer_group-in_standard_filter",
			"Customer-mobile_no-description",
			"Customer-email_id-in_standard_filter",
			"Customer-mobile_no-in_standard_filter",
			"Customer-email_id-in_list_view",
			"Customer-mobile_no-in_list_view",
			"Customer-customer_group-in_list_view",
			"Customer-default_currency-reqd",
			"Customer-customer_name-read_only",
			"Customer-account_manager-hidden",
			"Customer-gender-hidden",
			"Customer-salutation-hidden",
			"Customer-main-quick_entry",
			"Customer-email_id-label",
			"Customer-mobile_no-label",
			"Customer-default_currency-fetch_from",
			"Customer-default_currency-default",
			"Customer-default_price_list-default",
			"Customer-customer_type-default",
			"Customer-main-search_fields",
			"Customer-column_break_38-hidden",
			"Customer-market_segment-hidden",
			"Customer-credit_limit_section-hidden",
			"Customer-lead_name-hidden",
			"Customer-default_bank_account-hidden",
			"Customer-naming_series-hidden",
			"Customer-naming_series-reqd",
			"Purchase Taxes and Charges-item_wise_tax_detail-allow_on_submit",
			"Purchase Taxes and Charges-base_tax_amount_after_discount_amount-allow_on_submit",
			"Purchase Taxes and Charges-base_total-allow_on_submit",
			"Purchase Taxes and Charges-base_tax_amount-allow_on_submit",
			"Purchase Taxes and Charges-total-allow_on_submit",
			"Purchase Taxes and Charges-tax_amount_after_discount_amount-allow_on_submit",
			"Purchase Taxes and Charges-tax_amount-allow_on_submit",
			"Purchase Taxes and Charges-rate-allow_on_submit",
			"Purchase Taxes and Charges-account_head-allow_on_submit",
			"Purchase Taxes and Charges-charge_type-allow_on_submit",
			"Sales Invoice Item-barcode-hidden",
			"Sales Invoice Item-discount_account-hidden",
			"Sales Invoice Item-discount_account-mandatory_depends_on",
			"Sales Invoice Item-target_warehouse-hidden",
			"Journal Entry-naming_series-options",
			"Journal Entry-remark-in_list_view",
			"Journal Entry-voucher_type-options",
			"Item Barcode-barcode-hidden",
			"Purchase Order-schedule_date-default",
			"Purchase Order-buying_price_list-fetch_from",
			"Purchase Order-currency-fetch_from",
			"Purchase Order-base_rounded_total-hidden",
			"Purchase Order-base_rounded_total-print_hide",
			"Purchase Order-rounded_total-hidden",
			"Purchase Order-rounded_total-print_hide",
			"Purchase Order-in_words-hidden",
			"Purchase Order-in_words-print_hide",
			"Purchase Order-main-default_print_format",
			"Purchase Order-due_date-print_hide",
			"Purchase Order-payment_schedule-print_hide",
			"Purchase Order-supplier_name-in_list_view",
			"Purchase Order-transaction_date-in_list_view",
			"Purchase Order-grand_total-in_list_view",
			"Purchase Order-per_billed-in_list_view",
			"Purchase Order-per_received-in_list_view",
			"Purchase Order-section_addresses-collapsible",
			"Purchase Order-shipping_address-reqd",
			"Purchase Order-currency_and_price_list-collapsible",
			"Purchase Order-scan_barcode-hidden",
			"Purchase Order-base_total_taxes_and_charges-allow_on_submit",
			"Purchase Order-base_taxes_and_charges_added-allow_on_submit",
			"Purchase Order-taxes_and_charges_added-allow_on_submit",
			"Purchase Order-total_taxes_and_charges-allow_on_submit",
			"Purchase Order-base_grand_total-allow_on_submit",
			"Purchase Order-grand_total-allow_on_submit",
			"Purchase Order-base_in_words-allow_on_submit",
			"Purchase Order-in_words-allow_on_submit",
			"Purchase Order-rounded_total-allow_on_submit",
			"Purchase Order-base_rounded_total-allow_on_submit",
			"Purchase Order-taxes-allow_on_submit",
			"Purchase Order-base_taxes_and_charges_deducted-allow_on_submit",
			"Purchase Order-taxes_and_charges_deducted-allow_on_submit",
			"Purchase Order-ais_queue_failed-allow_on_submit",
			"Purchase Order-ais_queue_status-allow_on_submit",
			"Purchase Order-ais_queueu_comment-allow_on_submit",
			"Purchase Order-ais_queued_date-allow_on_submit",
			"Purchase Order-ais_queued_by-allow_on_submit",
			"Item Supplier-ifw_supplier_qoh-translatable",
			"Lead Source-main-field_order",
			"Stock Reconciliation-naming_series-options",
			"Stock Reconciliation-purpose-default",
			"Stock Reconciliation-cost_center-in_list_view",
			"Stock Reconciliation-ais_queue_failed-allow_on_submit",
			"Stock Reconciliation-ais_queue_status-allow_on_submit",
			"Stock Reconciliation-ais_queueu_comment-allow_on_submit",
			"Stock Reconciliation-ais_queued_date-allow_on_submit",
			"Stock Reconciliation-ais_queued_by-allow_on_submit",
			"Material Request-naming_series-options",
			"Material Request-scan_barcode-hidden",
			"Coupon Code-main-field_order",
			"Stock Zeroing Tool-naming_series-options",
			"Purchase Order-ais_queued_by-no_copy",
			"Purchase Order-ais_queued_date-no_copy",
			"Purchase Order-ais_queueu_comment-no_copy",
			"Purchase Order-ais_queue_status-no_copy",
			"Purchase Order-ais_queue_failed-no_copy",
			"Purchase Order-main-field_order",
			"Stock Reconciliation-ais_queue_status-read_only",
			"Stock Reconciliation-main-field_order",
			"STE Packing Slip-naming_series-options",
			"Customer-main-field_order",
			"Item-naming_series-hidden",
			"Sales Order Item-main-field_order",
			"Project-naming_series-options",
			"Bank Transaction-naming_series-default",
			"Bank Transaction-naming_series-options",
			"Payment Request-naming_series-options",
			"Pricing Rule-naming_series-default",
			"Pricing Rule-naming_series-options",
			"POS Invoice-naming_series-options",
			"Webhook-naming_series-options",
			"Opportunity-naming_series-options",
			"Purchase Invoice Item-from_warehouse-hidden",
			"Delivery Note Item-target_warehouse-hidden",
			"POS Invoice-scan_barcode-hidden",
			"Cycle Count-scan_barcode-hidden",
			"Cycle Count V2-scan_barcode-hidden",
			"POS Invoice Item-barcode-hidden",
			"Attendance-naming_series-options",
			"Purchase Invoice Item-discount_account-mandatory_depends_on",
			"Purchase Invoice Item-discount_account-hidden",
			"Campaign-naming_series-options",
			"Packed Item-rate-read_only",
			"Lead-naming_series-options",
			"Salary Slip-rounded_total-print_hide",
			"Salary Slip-rounded_total-hidden",
			"Delivery Note Item-so_detail-hidden",
			"Contact-phone_nos-description",
			"Supplier Quotation-in_words-print_hide",
			"Supplier Quotation-in_words-hidden",
			"Supplier Quotation-rounded_total-print_hide",
			"Supplier Quotation-rounded_total-hidden",
			"Supplier Quotation-base_rounded_total-print_hide",
			"Supplier Quotation-base_rounded_total-hidden",
			"Prepared Report-allow_auto_repeat",
			"Auto Repeat-allow_auto_repeat",
			"Shipstation API Requests-naming_series-options",
			"Sales Taxes and Charges-total-precision",
			"Sales Taxes and Charges-tax_amount-precision",
			"Suspended Invoice Item-barcode-hidden",
			"POS Closing Voucher Invoices-default_print_format",
			"Job Card-barcode-hidden",
			"Delivery Note Item-barcode-hidden",
			"Clinical Procedure Item-barcode-hidden",
			"Item-serial_nos_and_batches-hidden",
			"Contact-designation-hidden",
			"Contact-more_info-hidden",
			"Timesheet-naming_series-options",
			"Tax Rule-sales_tax_template-in_list_view",
			"Dropbox Settings-dropbox_access_key-hidden",
			"Dropbox Settings-dropbox_access_secret-hidden",
			"Dropbox Settings-dropbox_access_token-hidden",
			"Contact-last_name-translatable",
			"Contact-first_name-translatable",
			"GL Entry-autoname",
			"Tax Rule-autoname",
			"Stock Ledger Entry-autoname",
			"Sales Taxes and Charges-autoname",
			"Bin-autoname",
			"Custom Field-label-width",
			"Shipment Parcel-weight-precision",
			"Material Request-transfer_status-no_copy",
			"Stock Reconciliation Item-current_amount-permlevel",
			"Stock Reconciliation Item-current_valuation_rate-permlevel",
			"Stock Reconciliation Item-amount-permlevel",
			"Item Price-price_list_rate-permlevel",
			"Stock Reconciliation Item-valuation_rate-permlevel",
			"Stock Entry Detail-additional_cost-permlevel",
			"Stock Entry Detail-base_rate-permlevel",
			"Stock Entry Detail-valuation_rate-permlevel",
			"Stock Entry Detail-amount-permlevel",
			"Stock Entry Detail-basic_amount-permlevel",
			"Purchase Order Item-base_amount-permlevel",
			"Purchase Order Item-last_purchase_rate-permlevel",
			"Purchase Order Item-amount-permlevel",
			"Purchase Order Item-base_net_amount-permlevel",
			"Purchase Order Item-net_amount-permlevel",
			"Purchase Order Item-base_net_rate-permlevel",
			"Purchase Order Item-net_rate-permlevel",
			"Purchase Order Item-base_rate-permlevel",
			"Purchase Order Item-base_price_list_rate-permlevel",
			"Purchase Order Item-price_list_rate-permlevel",
			"Purchase Order Item-rate-permlevel",
			"Purchase Receipt Item-billed_amt-permlevel",
			"Purchase Receipt Item-base_net_amount-permlevel",
			"Purchase Receipt Item-net_amount-permlevel",
			"Purchase Receipt Item-base_net_rate-permlevel",
			"Purchase Receipt Item-net_rate-permlevel",
			"Purchase Receipt Item-base_amount-permlevel",
			"Purchase Receipt Item-amount-permlevel",
			"Purchase Receipt Item-base_price_list_rate-permlevel",
			"Purchase Receipt Item-price_list_rate-permlevel",
			"Work Order-wip_warehouse-default",
			"Work Order-fg_warehouse-default",
			"Work Order-source_warehouse-default"
		]]]
	},
  	{
		"dt": "Provinces"
	},
	{
		"dt": "City Symbol"
	},
	{
		"dt": "Email Template",
		"filters": [["name", "in", [
			"POS User Welcome Email"
		]]]
	}
]

#For using in print format
jinja = {
	"methods": [
		"metactical.custom_scripts.purchase_order.purchase_order.get_po_items",
		"metactical.custom_scripts.purchase_receipt.purchase_receipt.get_pr_items",
		"metactical.barcode_generator.get_barcode",
		"metactical.custom_scripts.sales_invoice.sales_invoice.si_mode_of_payment",
		"metactical.barcode_generator.get_barcode_for_print_format",
		"metactical.metactical.doctype.ste_packing_slip.ste_packing_slip.get_item_details_for_print",
 		"metactical.custom_scripts.utils.metactical_utils.get_password",
		"metactical.custom_scripts.utils.metactical_utils.sort_items_by_location",
		"metactical.barcode_generator.get_qr_for_print_format",
		"metactical.custom_scripts.utils.metactical_utils.custom_parse_json"
	]
}


# app_include_python = [
#     "metactical.custom_scripts.rabbitmq.integration.subscribe_to_rabbitmq"
# ]